### PR TITLE
Switch to analytics-node to support webkom/analytics

### PR DESCRIPTION
**Pull request by eirsyl**

### CODE REVIEW

**Comment by eirsyl** [comment]
@larseen

**Comment by larseen** [comment]
Looks good, does this work in dev when you dont have an analytics server to send data to?
What happends if the analytics server is down or unreachable?

**Comment by eirsyl** [comment]
The test passes without an Analytics server on CI 😎
fre. 3. mar. 2017 kl. 10.40 skrev Kristoffer K Larsen <
notifications@github.com>:

**Comment by larseen** [comment]
🥇

**Pull request merged**
